kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    kfctl.kubeflow.io/kfdef-instance: opendatahub.odh
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image with minimal dependency set to start experimenting
      with Jupyter environment.
    opendatahub.io/notebook-image-name: DJW Customized Notebook
    opendatahub.io/notebook-image-order: '1'
    opendatahub.io/notebook-image-url: >-
      https://github.com/djw-opendatahub-io/notebooks/tree/main/jupyter/minimal/ubi8-python-3.8
  name: djw-jupyter-minimal-notebook
  namespace: odh
  labels:
    component.opendatahub.io/name: notebooks
    opendatahub.io/component: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: py3.9-v1
      annotations:
        opendatahub.io/default-image: 'true'
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"JupyterLab","version": "3.2"}, {"name":
          "Notebook","version": "6.4"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.9"}]'
        openshift.io/imported-from: quay.io/opendatahub/notebooks
      from:
        kind: DockerImage
        name: image-registry.openshift-image-registry.svc:5000/custom-nb/djw-ubi9
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Local