---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data
  namespace: nexus
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi

---
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
    deployment.kubernetes.io/revision: '1'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"nexus3:latest","namespace":"nexus"},"fieldPath":"spec.template.spec.containers[?(@.name==\"nexus3\")].image","pause":"false"}]
  name: nexus3
  generation: 1
  namespace: nexus
  labels:
    app: nexus3
    app.kubernetes.io/component: nexus3
    app.kubernetes.io/instance: nexus3
    app.kubernetes.io/name: nexus3
    app.kubernetes.io/part-of: nexus3-app
    app.openshift.io/runtime-namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus3
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nexus3
        deployment: nexus3
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      volumes:
        - name: nexus3-1
          persistentVolumeClaim:
            claimName: nexus-data
      containers:
        - name: nexus3
          image: sonatype/nexus3
          ports:
            - containerPort: 8081
              protocol: TCP
          resources: 
            limits:
              cpu: "4"
            requests:
              cpu: "2"          
          volumeMounts:
            - name: nexus3-1
              mountPath: /nexus-data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
kind: Service
apiVersion: v1
metadata:
  name: nexus3
  namespace: nexus
  labels:
    app: nexus3
    app.kubernetes.io/component: nexus3
    app.kubernetes.io/instance: nexus3
    app.kubernetes.io/name: nexus3
    app.kubernetes.io/part-of: nexus3-app
    app.openshift.io/runtime-version: latest
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  clusterIP: 172.30.29.213
  ipFamilies:
    - IPv4
  ports:
    - name: 8081-tcp
      protocol: TCP
      port: 8081
      targetPort: 8081
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.30.29.213
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: nexus3
    deployment: nexus3

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: nexus3
  namespace: nexus
  labels:
    app: nexus3
    app.kubernetes.io/component: nexus3
    app.kubernetes.io/instance: nexus3
    app.kubernetes.io/name: nexus3
    app.kubernetes.io/part-of: nexus3-app
    app.openshift.io/runtime-version: latest
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: nexus3-nexus.apps.ocp4.davenet.local
  to:
    kind: Service
    name: nexus3
    weight: 100
  port:
    targetPort: 8081-tcp
  wildcardPolicy: None
